[project]
name = "Comfyui-Resolution-Master"
description = "test"
version = "1.0"
license = { text = "MIT License" }

[project.urls]
Repository = "https://github.com/Azornes/Comfyui-Resolution-Master"

[tool.comfy]
PublisherId = "azornes"
DisplayName = "Comfyui-Resolution-Master"
Icon = ""
