name: ðŸ“ Documentation Request
description: Suggest improvements or additions to documentation
title: "[Docs] "
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        > This template is only for suggesting improvements or additions **to existing documentation**.  
        > If you want to suggest a new feature, functionality, or enhancement for the project itself, please use the **Feature Request** template instead.  
        > Thank you!
  - type: input
    id: doc_area
    attributes:
      label: Area of documentation
      placeholder: e.g. Features, Installation, Known Issues / Compatibility
    validations:
      required: true
  - type: textarea
    id: current_issue
    attributes:
      label: What's wrong or missing?
      placeholder: Describe the gap or confusing part
    validations:
      required: true
  - type: textarea
    id: suggested_content
    attributes:
      label: How should it be improved?
      placeholder: Provide concrete suggestions or examples
